sudo: false
language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run
script:
  - tox

deploy:
  - provider: pypi
    user: ${PYPI_USER}
    password: ${PYPI_PASSWORD}
    server: https://testpypi.python.org/pypi
    on:
      branch: master
  - provider: pypi
    user: ${PYPI_USER}
    password: ${PYPI_PASSWORD}
    on:
      tags: true
