sudo: false
language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run
script:
  - tox

deploy:
  - provider: pypi
    skip_existing: true
    user: ${PYPI_USER}
    password:
      secure: ${PYPI_PASSWORD}
    server: https://pypi.pypi.org/legacy/
    on:
      branch: master
  - provider: pypi
    user: ${PYPI_USER}
    password:
      secure: ${PYPI_PASSWORD}
    server: https://pypi.pypi.org/legacy/
    on:
      tags: true
